name: Validate and Deploy HAProxy Controller helm charts to Development

on:
  workflow_dispatch:
    inputs:
      HAPROXY_HELM_CHART_VERSION:
        description: "The version of the HAProxy Controller to install"
        required: true
        default: "1.46.1"

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/helm-charts.yaml@main
    with:
      RELEASE_NAME: haproxy
      NAMESPACE: haproxy-controller
      CHART_REPO_NAME: haproxytech
      CHART_REPO_URL: https://haproxytech.github.io/helm-charts
      CHART_NAME: kubernetes-ingress
      CHART_VERSION: ${{ github.inputs.HAPROXY_HELM_CHART_VERSION }}
      CHART_PATH: ./haproxy-controller
      VALUES_FILES: "./haproxy-controller/values.yaml ./haproxy-controller/values/values_dev.yaml"
    secrets: inherit